###
GET http://localhost:3000/api/blog/articlelist?pagenum=1&pagesize=10 HTTP/1.1

###
# @name loginAdmin
POST http://localhost:3000/api/login/users HTTP/1.1
Content-Type: application/json

{
    "username":"admin",
    "password":"123456"
}

###
GET http://localhost:3000/api/admin/users HTTP/1.1
Authorization: Bearer {{loginAdmin.response.body.token}}

###
GET http://localhost:3000/api/blog/getme HTTP/1.1
Authorization: Bearer {{loginAdmin.response.body.token}}

###
POST http://localhost:3000/api/user/add HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{loginAdmin.response.body.token}}

{
    "email": "123",
    "username":"admin3",
    "password":"123456"
}